# Generated by Django 4.0.4 on 2022-05-05 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=200, unique=True),
        ),
    ]
