# Generated by Django 4.0.4 on 2022-05-05 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 7, 31, 55, 256901)),
        ),
    ]
